openapi: 3.0.1
tags:
- name: Webhook
  description: The following chapter will give you an overview about the Webhook.
paths:
  /external/webhook:
    post:
      tags:
      - Webhook
      summary: Provide a webhook response
      description: "Provide a new response for a existing subscription, which will\
        \ be delivered to all subscribers."
      operationId: receiveWebhookRequest
      parameters:
      - name: x-WEBHOOKUSER
        in: header
        schema:
          type: string
      requestBody:
        description: File passed by the status provider
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
      security:
      - BASIC: []
components:
  schemas:
    APIErrorResponse:
      type: object
      properties:
        error_code:
          $ref: '#/components/schemas/ApiError'
        error_message:
          type: string
        error_source:
          type: string
    ApiError:
      type: object
      properties:
        errorMessage:
          type: string
  securitySchemes:
    BASIC:
      type: http
      description: Basic Auth
      scheme: Basic
